/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.sauces.aplicacionNomina1.vista;

import es.sauces.aplicacionNomina1.controlador.Controlador;
import es.sauces.aplicacionNomina1.modelo.Empleado;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Usuario
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        selectorFicheros = new javax.swing.JFileChooser();
        panelDatos = new javax.swing.JPanel();
        etiquetaDni = new javax.swing.JLabel();
        textFieldDni = new javax.swing.JTextField();
        etiquetaNombre = new javax.swing.JLabel();
        textFieldNombre = new javax.swing.JTextField();
        etiquetaTipo = new javax.swing.JLabel();
        comboBoxTipo = new javax.swing.JComboBox<>();
        etiquetaSalario = new javax.swing.JLabel();
        jFormattedTextFieldSalario = new javax.swing.JFormattedTextField();
        etiquetaIngresos = new javax.swing.JLabel();
        etiquetaHoras = new javax.swing.JLabel();
        spinnerHoras = new javax.swing.JSpinner();
        jFormattedTextFieldIngresos = new javax.swing.JFormattedTextField();
        botonBorrar = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        panelListado = new javax.swing.JPanel();
        botonListarEmpleados = new javax.swing.JButton();
        radioButtonDni = new javax.swing.JRadioButton();
        radioButtonNombre = new javax.swing.JRadioButton();
        radioButtonIngresos = new javax.swing.JRadioButton();
        etiquetaOrdenListado = new javax.swing.JLabel();
        jScrollPaneListarEmpleados = new javax.swing.JScrollPane();
        tablaEmpleado = new javax.swing.JTable();
        menuPrincipal = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuItemAbrir = new javax.swing.JMenuItem();
        menuItemGuardar = new javax.swing.JMenuItem();
        menuEmpleado = new javax.swing.JMenu();
        menuItemNuevo = new javax.swing.JMenuItem();
        menuItemBuscar = new javax.swing.JMenuItem();

        selectorFicheros.setCurrentDirectory(new java.io.File("."));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de nóminas");
        setResizable(false);

        panelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del empleado"));

        etiquetaDni.setText("DNI");

        textFieldDni.setEditable(false);

        etiquetaNombre.setText("NOMBRE");

        etiquetaTipo.setText("TIPO");

        comboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIJO", "EVENTUAL" }));
        comboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt){
                comboBoxTipoActionPerformed(evt);
            }
        });
        comboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTipoActionPerformed(evt);
            }
        });

        etiquetaSalario.setText("SALARIO");

        etiquetaIngresos.setText("INGRESOS");

        etiquetaHoras.setText("HORAS");

        botonBorrar.setBackground(new java.awt.Color(51, 153, 255));
        botonBorrar.setText("BORRAR");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        botonModificar.setBackground(new java.awt.Color(51, 153, 255));
        botonModificar.setText("MODIFICAR");
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiquetaIngresos))
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(botonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDatosLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jFormattedTextFieldIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaNombre)
                            .addComponent(etiquetaTipo)
                            .addComponent(etiquetaSalario)
                            .addComponent(etiquetaDni, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiquetaHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinnerHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(comboBoxTipo, javax.swing.GroupLayout.Alignment.LEADING, 0, 126, Short.MAX_VALUE)
                                .addComponent(textFieldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textFieldDni, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFormattedTextFieldSalario)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaDni))
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNombre)
                    .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaTipo))
                .addGap(25, 25, 25)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaSalario)
                    .addComponent(jFormattedTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaHoras)
                    .addComponent(spinnerHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaIngresos, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFormattedTextFieldIngresos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBorrar)
                    .addComponent(botonModificar)))
        );

        panelListado.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de empleados"));

        botonListarEmpleados.setBackground(new java.awt.Color(51, 153, 255));
        botonListarEmpleados.setText("LISTAR EMPLEADOS");
        botonListarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListarEmpleadosActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioButtonDni);
        radioButtonDni.setSelected(true);
        radioButtonDni.setText("DNI");
        radioButtonDni.setActionCommand("bDNI");

        buttonGroup1.add(radioButtonNombre);
        radioButtonNombre.setText("NOMBRE");
        radioButtonNombre.setActionCommand("bNOMBRE");

        buttonGroup1.add(radioButtonIngresos);
        radioButtonIngresos.setText("INGRESOS");
        radioButtonIngresos.setActionCommand("bINGRESOS");

        etiquetaOrdenListado.setText("ORDEN DEL LISTADO");

        empleadoTM=new EmpleadoTableModel();
        tablaEmpleado.setModel(empleadoTM);
        tablaEmpleado.getSelectionModel().addListSelectionListener(
            new ListSelectionListener(){
                public void valueChanged(ListSelectionEvent lse){
                    int fila=tablaEmpleado.getSelectedRow();
                    if(fila>=0){
                        mostrarDni(tablaEmpleado.getValueAt(fila,0).toString());
                        mostrarNombre((String)tablaEmpleado.getValueAt(fila, 1));
                        mostrarSalario((float)tablaEmpleado.getValueAt(fila, 2));
                        int horas=(int)tablaEmpleado.getValueAt(fila, 3);
                        mostrarHoras(horas);
                        if(horas==0){
                            mostrarTipo("FIJO");
                        }else{
                            mostrarTipo("EVENTUAL");
                        }
                        mostrarIngresos((float)tablaEmpleado.getValueAt(fila, 4));
                    }
                }
            });
            jScrollPaneListarEmpleados.setViewportView(tablaEmpleado);

            javax.swing.GroupLayout panelListadoLayout = new javax.swing.GroupLayout(panelListado);
            panelListado.setLayout(panelListadoLayout);
            panelListadoLayout.setHorizontalGroup(
                panelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelListadoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPaneListarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelListadoLayout.createSequentialGroup()
                            .addComponent(etiquetaOrdenListado)
                            .addGap(35, 35, 35)
                            .addComponent(radioButtonDni)
                            .addGap(51, 51, 51)
                            .addComponent(radioButtonNombre)
                            .addGap(33, 33, 33)
                            .addComponent(radioButtonIngresos))))
                .addGroup(panelListadoLayout.createSequentialGroup()
                    .addGap(144, 144, 144)
                    .addComponent(botonListarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
            );
            panelListadoLayout.setVerticalGroup(
                panelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelListadoLayout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(botonListarEmpleados)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPaneListarEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                    .addGap(48, 48, 48)
                    .addGroup(panelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radioButtonDni)
                        .addComponent(radioButtonNombre)
                        .addComponent(radioButtonIngresos)
                        .addComponent(etiquetaOrdenListado))
                    .addGap(22, 22, 22))
            );

            menuArchivo.setText("Archivo");

            menuItemAbrir.setText("Abrir...");
            menuItemAbrir.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    menuItemAbrirActionPerformed(evt);
                }
            });
            menuArchivo.add(menuItemAbrir);

            menuItemGuardar.setText("Guardar...");
            menuItemGuardar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    menuItemGuardarActionPerformed(evt);
                }
            });
            menuArchivo.add(menuItemGuardar);

            menuPrincipal.add(menuArchivo);

            menuEmpleado.setText("Empleado");

            menuItemNuevo.setText("Nuevo...");
            menuItemNuevo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    menuItemNuevoActionPerformed(evt);
                }
            });
            menuEmpleado.add(menuItemNuevo);

            menuItemBuscar.setText("Buscar...");
            menuItemBuscar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    menuItemBuscarActionPerformed(evt);
                }
            });
            menuEmpleado.add(menuItemBuscar);

            menuPrincipal.add(menuEmpleado);

            setJMenuBar(menuPrincipal);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(panelListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed

    }//GEN-LAST:event_bAceptarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed

    }//GEN-LAST:event_bCancelarActionPerformed

    private void comboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTipoActionPerformed
        if (comboBoxTipo.getSelectedItem().equals("FIJO")) {
            this.etiquetaHoras.setVisible(false);
            this.spinnerHoras.setVisible(false);
        } else {
            this.etiquetaHoras.setVisible(true);
            this.spinnerHoras.setVisible(true);
        }
    }//GEN-LAST:event_comboBoxTipoActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        controlador.modificarEmpleado();
    }//GEN-LAST:event_botonModificarActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        mostrarDni(JOptionPane.showInputDialog("Introduce el DNI del empleado a eliminar"));
        controlador.eliminarEmpleado();
        limpiarCampos();
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void menuItemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAbrirActionPerformed
        if (selectorFicheros.showOpenDialog(this) == selectorFicheros.APPROVE_OPTION) {
            controlador.cargarEmpleados();
        }
    }//GEN-LAST:event_menuItemAbrirActionPerformed

    private void menuItemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGuardarActionPerformed
        if (selectorFicheros.showSaveDialog(this) == selectorFicheros.APPROVE_OPTION) {
            controlador.guardarEmpleados();
        }
    }//GEN-LAST:event_menuItemGuardarActionPerformed

    private void botonListarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListarEmpleadosActionPerformed
        controlador.listarEmpleados();
    }//GEN-LAST:event_botonListarEmpleadosActionPerformed

    private void menuItemNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNuevoActionPerformed
        dialogoEmpleado.limpiarCampos();
        if (dialogoEmpleado.mostrar() == DialogoEmpleado.ACEPTAR) {
            mostrarDni(dialogoEmpleado.getDni());
            mostrarNombre(dialogoEmpleado.getNombre());
            String tipo = dialogoEmpleado.getTipo();
            mostrarTipo(tipo);
            mostrarSalario(dialogoEmpleado.getSalario());
            if (tipo == "EVENTUAL") {
                mostrarHoras(dialogoEmpleado.getHoras());
            }
            controlador.crearEmpleado();
        }
    }//GEN-LAST:event_menuItemNuevoActionPerformed

    private void menuItemBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBuscarActionPerformed
        mostrarDni(JOptionPane.showInputDialog("Introduce el DNI del empleado a buscar"));
        limpiarCampos();
        controlador.buscarEmpleado();
    }//GEN-LAST:event_menuItemBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    public String getDni() {
        return textFieldDni.getText();
    }

    public String getNombre() {
        return textFieldNombre.getText();
    }

    public float getSalario() {
        return Float.parseFloat(this.jFormattedTextFieldSalario.getText().replace(',', '.'));
    }

    public int getHoras() {
        return (int) spinnerHoras.getValue();
    }
    
    public String getTipo(){
        return this.comboBoxTipo.toString();
    }

    public String getOrden() {
        return this.buttonGroup1.getSelection().getActionCommand();
    }

    public void listarEmpleados(List<Empleado> listado) {
        empleadoTM.setListado(listado);
        empleadoTM.fireTableDataChanged();
    }

    public String getArchivo() {
        return selectorFicheros.getSelectedFile().getAbsolutePath();
    }

    public void mostrarTipo(String tipo) {
        comboBoxTipo.setSelectedItem(tipo);
    }

    public void mostrarDni(String dni) {
        textFieldDni.setText(dni);
    }

    public void mostrarNombre(String nombre) {
        textFieldNombre.setText(nombre);
    }

    public void mostrarSalario(float salario) {
        jFormattedTextFieldSalario.setValue(salario);
    }

    public void mostrarHoras(int horas) {
        spinnerHoras.setValue(horas);
    }

    public void mostrarIngresos(float ingresos) {
        jFormattedTextFieldIngresos.setValue(ingresos);
    }

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }

    public boolean solicitarConfirmacion() {
        if (JOptionPane.showConfirmDialog(this, "¿Está seguro?", "", JOptionPane.YES_NO_CANCEL_OPTION) == JOptionPane.YES_OPTION) {
            return true;
        } else {
            return false;
        }
    }

    public void limpiarCampos() {
        this.textFieldDni.setText("");
        this.textFieldNombre.setText("");
        this.jFormattedTextFieldSalario.setText("");
        this.jFormattedTextFieldIngresos.setText("");
    }

    public void mostrar() {
        setVisible(true);
    }

    private Controlador controlador;
    private EmpleadoTableModel empleadoTM;
    private DialogoEmpleado dialogoEmpleado = new DialogoEmpleado(this, true);

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonListarEmpleados;
    private javax.swing.JButton botonModificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboBoxTipo;
    private javax.swing.JLabel etiquetaDni;
    private javax.swing.JLabel etiquetaHoras;
    private javax.swing.JLabel etiquetaIngresos;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaOrdenListado;
    private javax.swing.JLabel etiquetaSalario;
    private javax.swing.JLabel etiquetaTipo;
    private javax.swing.JFormattedTextField jFormattedTextFieldIngresos;
    private javax.swing.JFormattedTextField jFormattedTextFieldSalario;
    private javax.swing.JScrollPane jScrollPaneListarEmpleados;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuEmpleado;
    private javax.swing.JMenuItem menuItemAbrir;
    private javax.swing.JMenuItem menuItemBuscar;
    private javax.swing.JMenuItem menuItemGuardar;
    private javax.swing.JMenuItem menuItemNuevo;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelListado;
    private javax.swing.JRadioButton radioButtonDni;
    private javax.swing.JRadioButton radioButtonIngresos;
    private javax.swing.JRadioButton radioButtonNombre;
    private javax.swing.JFileChooser selectorFicheros;
    private javax.swing.JSpinner spinnerHoras;
    private javax.swing.JTable tablaEmpleado;
    private javax.swing.JTextField textFieldDni;
    private javax.swing.JTextField textFieldNombre;
    // End of variables declaration//GEN-END:variables

}
